### ISSUE TITLE
Laravel does not show the debug bar.

### ISSUE THREAD

**Issue by fumiya5863** [ryo-kozin/lamp_docker#1]
### Details
Laravel's debug bar is not displayed when it is turned on.

### cause

There is a mistake in the following writing style

Before correction
```
        <Directory /var/www/laravel>
                AllowOverride All
        </Directory>
```

After correction
```
        <Directory /var/www/html>
                AllowOverride All
        </Directory>
```

**Comment by ryo-kozin** [comment]
Ok. Thank you. If you have time, could you make a pull request?

**Comment by fumiya5863** [comment]
OK

**Comment by ryo-kozin** [comment]
The problem was solved by a good guy.
